### PR TITLE
Thaumcraft 4.2.2.1 - 4.2.3

### PR DESCRIPTION
**Pull request by Alheimerjung**

### CODE REVIEW

**Comment by goldbattle** [comment]
Wow! Those are some amazing icons there. You made those all yourself? Is so, those are really impressive. Couple things, are the 4 crate images (top, 0, 1,2) suppose to have a shadow? [Link](https://github.com/Alheimerjung/Modded-1.7.x/blob/ea1e14dc8dcc35fb8f91be4a0a02c6a5985a2cd3/Thaumcraft_4/assets/thaumcraft/textures/blocks/crate_side_0.png). Wand table is suppose to have that small shadow? [Link](https://github.com/Alheimerjung/Modded-1.7.x/blob/ea1e14dc8dcc35fb8f91be4a0a02c6a5985a2cd3/Thaumcraft_4/assets/thaumcraft/textures/models/wandtable.png).


Thoughts on these @zISKo666, I know you deal more with this mod them me.

**Comment by goldbattle** [comment]
Any comments about those shaddows?

> Couple things, are the 4 crate images (top, 0, 1,2) suppose to have a shadow? [Link](https://github.com/Alheimerjung/Modded-1.7.x/blob/ea1e14dc8dcc35fb8f91be4a0a02c6a5985a2cd3/Thaumcraft_4/assets/thaumcraft/textures/blocks/crate_side_0.png). Wand table is suppose to have that small shadow? [Link](https://github.com/Alheimerjung/Modded-1.7.x/blob/ea1e14dc8dcc35fb8f91be4a0a02c6a5985a2cd3/Thaumcraft_4/assets/thaumcraft/textures/models/wandtable.png).

**Comment by zISKo666** [comment]
The surrounding drop shadows shouldn't be there. Please remove them.
Everything else looking pretty good.

**Comment by artdude543** [comment]
Is this okay with you now? @goldbattle, @zISKo666

**Comment by artdude543** [comment]
@Alheimerjung Any chance the last issue being fixed soon? Willing to pull this as soon as that last issue is fixed; as mentioned above.

**Pull request merged**
