### PR TITLE
ProjectRed: updated to current

### PR DESCRIPTION
**Pull request by QORTEC**
In the current versions of ProjectRed the assets layout has totally changed; this pull request mainly renames/moves the assets to their current place.

I've new to the whole commit/pull-request system, if there are any issues please let me and I will try to fix them.

### CODE REVIEW

**Comment by leagris** [comment]
I wonder if we shall put this in a distinct folder `/Project_Red_4_7/`, make distinct modid `projectred_4_7`, and keep older assets as-is for backward compatilility.

**Comment by artdude543** [comment]
Depends modpacks are pretty quick with updating Project Red due to its constant bugs fixing. @QORTEC If you could poke around and see what versions larger packs are using, then we can see if we need to support a back support also.

**Comment by QORTEC** [comment]
After looking around it looks like the majority of the modpack haven't updated ProjectRed, the majority are on ehter 4.6 or 4.5 [before the asset change].

In that case I should probably rename the folder and modid as stated above.

**Comment by artdude543** [comment]
Okay then thats a the plan :+1:

**Comment by QORTEC** [comment]
Currently I'm downloading your repo to replace the the Missing ProjectRed folder.
Can you pull the repo with just the name change, or do I have to put back the original ProjectRed folder?

**Comment by QORTEC** [comment]
Finished, if there there is anything else I need to do please let me know.

**Comment by artdude543** [comment]
support@soartex.net is the main one now. Best method of contact is using the contact form on the web site :)

**Comment by artdude543** [comment]
All our main gets redirected to the new one so either one will get an email to us, but the support one is the official new "address" for email support.

**Pull request merged**
