### PR TITLE
Enchanting Plus Add

### PR DESCRIPTION
**Pull request by NocturneBlock**
Adds enchantments and a more explicit enchanting UI to the game. All
textures included.

### CODE REVIEW

**Comment by artdude543** [comment]
Can we not just accept PR's please as this leads to problems example being: [default image](https://github.com/Soartex-Modded/Modded-1.7.x/blob/99fb213348e9ae4f563c8c6fa6080a71c420c4a8/Enchanting_Plus/assets/eplus/textures/gui/enchant.png)

**Comment by artdude543** [comment]
I know you want to add more textures but we have a checking policy for new textures. Which should be adhered too. Thanks.

**Comment by NocturneBlock** [comment]
Works for me, I suspected something like that, thus trying to split them up
so they can be reverted if needed. Can the checking policy be posted
somewhere prominent so it's easier to follow? The thread about submitting
textures only says how to do it if you're *not* using Github.

**Comment by goldbattle** [comment]
I think we just have a guide on how to push to github and make a PR
http://wiki.soartex.net/modded/01-02-2015/contributing-to-the-modded-repos/

**Comment by artdude543** [comment]
I'm going to remove all the textures I feel that don't match the style of the pack and those textures will have to be re-made and then submitted for approval. As we have an automated download system I don't want to see unapproved textures in the downloads. Please refrain from merging requests w/o prior authorisation / approval. As this has a knock on effect with our downloads and image.

**Comment by NocturneBlock** [comment]
Fine with me. I hadn't been able to find that guide, maybe link to it from
the Submission of Textures post on the forums. Also, something a bit
clearer about the process of vetting would be nice, like who does it, how
long one should be patient before poking to remind the evaluators that
there are textures in the queue, etc. That last is what got me; it's easier
to  be patient if you have some idea of what you're waiting for and the
order of magnitude of the wait.

Sorry I threw things off, but I am glad it got this conversation going.

Quinn

**Pull request merged**
