### PR TITLE
Mod Modular Systems - first commit

### PR DESCRIPTION
**Pull request by devanchya**
Signed-off-by: David Coley <David Coley>

### CODE REVIEW

**Comment by devanchya** [comment]
New modular - ModularSystems

**Comment by leagris** [comment]
@devanchya Can you fix your commit with a matching mod.json?

**Comment by devanchya** [comment]
fixed mods.json, editor didn't save correctly.  rookie mistake

**Comment by goldbattle** [comment]
It seems you removed all your png files in your last commit.

**Comment by devanchya** [comment]
did I fix my newbies to Git this time :)

**Comment by leagris** [comment]
You did it, thank you very much. And welcome to the world of Soartex modded contributors.

**Comment by goldbattle** [comment]
It looks like some of the textures are off centered. Along with that, the arrows have a very jagged appearance. The wood background is good, but the foreground textures need a bit of touch up. I would suggest making the textures look as though they are "inlayed" into the wood. They could be further improved but this is a good start. Up to you.

* `storageIO.png`
* `storageDir.png`
* `storageSide.png`

Example:
storagedir

**Pull request merged**
