### PR TITLE
Fixes for arrows

### PR DESCRIPTION
**Pull request by QuiOui**
Flipped most shafts horizontally to fit heads/fletchings. Added missing
textures.

### CODE REVIEW

**Comment by artdude543** [comment]
Have you tested the changes you made and what version of tinkers are you testing against?

**Comment by QuiOui** [comment]
I've tested the arrows with TConstruct-1.7.10-1.8.5.jar in Agrarian Skies 2.

**Comment by QuiOui** [comment]
Thinking about it more, you can't even make arrow shafts from metals any longer so most of the changes aren't required.

**Comment by artdude543** [comment]
Well other mods re-add the recipes so its worth keeping the textures, but as long as you've tested the textures and you're happy with them I will merge it in :)

**Comment by QuiOui** [comment]
As far as I can see they look fine, merge away.

**Pull request merged**
