### PR TITLE
Additions to Biomes_O_Plenty

### PR DESCRIPTION
**Pull request by NaiyasFury**
Added a few textures that haven't been done yet for Biomes_O_Plenty
version 1.7.10-2.1.0.1283-universal. (The hive and honeycomb textures may be too photorealistic, but I'm happy with them)

Here are the images I took in game:

### CODE REVIEW

**Comment by artdude543** [comment]
The textures of which are a concern to me are the following:

- The hive / honey blocks are far too realistic for what Soartex is. 
  - I'd like this removed before pulling.
- The apple block is not using the default Soartex texture.
  - If you don't mind re-creating this using the Soartex apple this would be amazing, otherwise would like that removed.
- The ender lotus is not fitting with the Soartex style and looks to be a resize.
  - Could this be removed also?
- Lastly the Flax Flowers stem looks to be very stretched.
  - You think you could edit them?

But apart from that all the other textures look amazing and I would like the merge them once the things I mentioned are fixed before hand. Thanks!

**Comment by Simon04090** [comment]
Any news on this? I would be especially interested in the hive and honey blocks because I wasn't to use them for the rooms I have my Forestry bees in. But I agree that these ones look far too photorealistic for Soartex. Also something I want to say you guys are doing a great job making modded Minecraft look so much better. Keep up the great work.

**Comment by artdude543** [comment]
I'm going to cherry pick the textures which fit the style and the mod in a bit. But the hives I'll look into creating the textures when I get a bit more free time.

**Comment by Simon04090** [comment]
That would be great.

**Comment by artdude543** [comment]
I've commited a cherry pick of the textures that work the best. Honey (Fluid) I'll add soon ish.

**Pull request closed without merging**
