### PR TITLE
ProjectE Mod Support

### PR DESCRIPTION
**Pull request by mizziness**
Modded Fanver texture support for the ProjectE mod version 1.9.4 for MC 1.7.10.  Fully tested locally.  All textures in the mod pack are complete - nothing left untextured.

projecte-soartext-1

projecte-soartext-2

projecte-soartext-3

### CODE REVIEW

**Comment by artdude543** [comment]
These look amazing! Thanks again will test in game and will pull shortly after ^_^

**Comment by goldbattle** [comment]
I really like these, some of the red is high on the saturation, but really good job!

**Comment by mizziness** [comment]
@goldbattle   Thank you :)  I agree with you on the red but I tried to keep it true to the colors of the original texture set.  I have PSDs and vector paths for all of the items I drew, so if you want me to make changes, I can easily do that ^.^

**Comment by artdude543** [comment]
So these look mostly fine to me just the same with Gold about the saturation being high on some textures. But these can easily be fixed. Thanks again for the help your work so far has been amazing! :D

**Comment by goldbattle** [comment]
:+1:

**Pull request merged**
