### PR TITLE
Ported Logistics Pipes + Greg's Lighting + Additional Buildcraft Objects

### PR DESCRIPTION
**Pull request by QORTEC**
I've ported over all the MC 1.6.4 assets to the current version of logistics pipes.

All textures should be unmodified except the listed ones below:
Logistics_Pipes/assets/textures/blocks/pipes/new_texture/*
Logistics_Pipes/assets/textures/items/pipeController.png

There are still a bunch of assets missing...

If there is anything else I should do please let me know.

### CODE REVIEW

**Comment by QORTEC** [comment]
I've also ported Greg's Lighting form MC 1.6.4 to the current version.
All textures are unmodified.

**Comment by artdude543** [comment]
I saw some 16x textures in the Logistics Pipes commit are these the right textures or misplaces from the default mod assets?

**Comment by QORTEC** [comment]
Are the 16x textures found in the new_texture folder?

**Comment by artdude543** [comment]
Yes default assets should not be included when creating patches.

**Comment by artdude543** [comment]
I will download these changes to see for myself but they should be at least x4 the original size.

**Comment by QORTEC** [comment]
All the LogisticsPipes assets are originally form the 1.6.4 branch of Soartex-Modded, below is a detailed list of changed/modified textures.
- added a transport pipe texture to the pack **blocks/pipes/transport/basic.png**
 - The transport pipe belongs in **blocks/pipes/overlay_gen/transport/basic.png** mod author will likely want to correct that later on
 - The transport pipe is a modified copy of **blocks/pipes/overlay_gen/basic/powered-pipe.png**
- Assets found in **blocks/pipes/new_textures/*** are 26x26px
 - These assets are 1:1 copies of the logos found on the pipes in the **pipes/overlay_gen/*/**.
 - I didn't downrez the images in order to maintain the maximum amount of quality possible.
 - I didn't uprez the files since there would be a loss of quality that I wouldn't likely be able to compensate for. [My image manipulation skills are fairly lackluster.]
- I added **items/pipeController.png**, it is visually identical to Network Monitor but red
 - I copied the Network Monitor in gimp, selected the yellow casing and used colourize option to change the yellow to red

That should explain all the changes, if you have any questions/suggestions please let me know.

**Comment by QORTEC** [comment]
ProjectRed:
- Added New Ore & Block
 - New assets can be found at **Project_Red_4_7/.../blocks/world/**
- Added New Items
 - New assets can be found at **Project_Red_4_7/.../items/base/**


LogisticsPipes:
- Added New Items
 - New modules can be found at **Logistics_Pipes/.../items/itemModule/**
 - New upgrades can be found at **Logistics_Pipes/.../items/itemUpgrade/**
- Changed 2 upgrades to be more recognizable when compared to original
 - Modified Crafting Byproduct
 - Changed Satelite to Power Transport

All "new" assets are modified existing Soartex textures.
Let if there is anything else I should do.

**Comment by QORTEC** [comment]
Ported Additional Buildcraft Objects assets form 1.6.4.

All new/modified textures can be found in **Additional_Buildcraft_Objects/.../blocks/**
- PipeItemsEnderExtract.png
- PipeItemsInsertLegacy.png
- PipeLiquidsInsertion.png
- PipeLiquidsValveClosedSide.png
- PipeLiquidsValveOpenSide.png

All textures are unmodified or based off of existing Soartex textures.

**Comment by QORTEC** [comment]
Ported AdditionalPipes assets form 1.4.x

All textures are unmodified Soartex textures.

**Comment by goldbattle** [comment]
Please use uppercase folder names.
On windows you will need to remove the folder, commit, and then re-add it with correct casing.
But if you change the name you can just recommit things.
I would recommend `Additional_Pipes`.

**Comment by QORTEC** [comment]
Fixed naming. If there is anything else that needs to be done please let me know.

**Comment by artdude543** [comment]
Looks all good to me. Thanks for your hard work :)

**Pull request merged**
