### PR TITLE
Botania - Tall Mystical Flowers

### PR DESCRIPTION
**Pull request by mizziness**
Botania - Adding textures for the new items, tall mystical flowers.  Done so far:  Blue, Black, Purple, Gray

### CODE REVIEW

**Comment by zISKo666** [comment]
Checked them ingame and they looking great.
Thank you for the commit.

**Comment by mizziness** [comment]
@zISKo666 No problem!  I just checked in a couple more, and I hope to finish the batch within the next day or so.  I'm glad you like!  :D

**Comment by mizziness** [comment]
Okay, that's all of them :D

**Comment by zISKo666** [comment]
Very nice. Thanks again for your commit :)
@artdude543 is it OK to merge? ;)

**Comment by artdude543** [comment]
Just gone over these now, sorry for the delay IRL is becoming a nightmare. But the textures seem fine work well with the other textures already made and such. I'd like to see these getting re-looked at later down the link to match the Vanilla style of flowers more. But for a mod texture these are amazing and far better than the default ones.

Great work and thanks for helping out! ^_^

**Comment by mizziness** [comment]
@artdude543   Thanks!  Totally understandable about real life :)  As a side note, I just bombarded you with a new merge request :D

**Pull request merged**
