### PR TITLE
feat(mod): super solar panels

### PR DESCRIPTION
**Pull request by leagris**
add the mod textures folder with mod.json
add the blocks textures

### CODE REVIEW

**Comment by artdude543** [comment]
👍

**Comment by artdude543** [comment]
Is this completed to be merged in?

**Comment by leagris** [comment]
> Is this completed to be merged in?

Waiting for @Tedtricks to do the Items and it will be all good soon.

**Comment by leagris** [comment]
Thanks to @Tedtricks for these nice contributions.

**Pull request merged**
