### PR TITLE
ExtraBiomesXL Import and Magical Crops update

### PR DESCRIPTION
**Pull request by Mystara0001**
Imported ExtraBiomesXL from 1.6.x and add some new textures. Updated
Magical Crops to include existing textures added some crops to match the
current theme. Changed the mCropDye_3.png.mcmeta to massively slow down
the animation of Dye Essence crops.

### CODE REVIEW

**Comment by artdude543** [comment]
Which version of magical crops did you use? The version on the old forum thread or the version in Sky Factory 2 (Which is going to be the version were supporting) As I dropped support from the old versiona while back and its going to stay that way till the Magical Crops 4 is released.

**Comment by Mystara0001** [comment]
The version from the Regrowth Mod Pack.

**Comment by artdude543** [comment]
Version number?

**Comment by Mystara0001** [comment]
This should be posted somewhere so that people don't waste their time making changes to the mod textures for nothing. No one knows you aren't accepting anything for a Magical Crops version that hasn't even been released yet. Can you provide a link to the as of yet unfinished mod so that I can see how much of my current work is salvageable?

It is my opinion that textures should not be put on hold because a newer version of a mod "may be" released. There are plenty of packs that still use the 3.x versions and it shouldn't be an issue to support both versions. Since it is contributors that do a lot of the work on the textures, they should be allowed to decide if something is worth updating.

**Comment by artdude543** [comment]
It's not a matter of "wasting" time as the mod textures are changed in the new version. So if we merge these textures they will have to be updated again when the main mod is released so really I'm saving you the hassle with having to update them. The current textures in the repo now support the beta version. (Which you can find in the Sky Factory Pack download)

We're not putting textures on hold just supporting the version which are being updated and maintained, the other version is not having any more updates. I contribute a lot of work to the modded side and watch which versions of mods are current, and this is the rare case where we will only support the beta compared the the "mainstream" version.

I appreciate the feedback, but this is how the system has worked for Soartex modded support. We try to keep with the current versions which the majority of people are using in this case the beta is used more.

**Comment by goldbattle** [comment]
If the textures are compatible with both versions go for that. The `mod.json` for this mod is incorrect, so sorry about the confusion. Usually we don't support beta versions, but because of the high download volume that a popular modpack like sky factory brings, we want to provide a good experience to the majority of people.

That being said, if both version can be supported at once, go for it. It is looking like there is some additions of textures that shouldn't effect the beta. That being said, test them with both versions please.

The extrabiome textures all look good, thanks again for porting it. Could you please make a mod.json file for it. Instruction can be found here:
http://wiki.soartex.net/modded/02-04-2015/making-a-modpack-json/

**Comment by goldbattle** [comment]
Oh my goodness, sorry about that, I was not paying attention to what I was linking you. Sorry to put you through that work, here is the correct link:
http://wiki.soartex.net/modded/01-01-2015/making-a-mod-json/

My apologies totally my fault, and sorry to make you go through that.
Here is is the `mod.json` to save you the time from going through it all again.
```json
{
  "mod_id": "ExtrabiomesXL",
  "mod_name": "Extra Biomes XL",
  "mod_dir": "/ExtraBiomesXL/",
  "mod_version": "v3.16.0",
  "mc_version": "1.7.x",
  "mod_authors": ["ScottKillen","allaryin","JLBShecky","aivukuro","bspkrs","gwydion0917","ebxl-Zenth","Annysia"],
  "url_website": "http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1282126-extrabiomesxl-universal-3-16-0-for-mc-1-7-10",
  "description": "ExtrabiomesXL is a collaborative open source mod for Minecraft which adds new biomes and an assortment of natural blocks and items that enhance gameplay."
}
```
I have also talked to @artdude543 and he says the beta is incompatible with older versions.

**Comment by Mystara0001** [comment]
So what do I need to do to correct this pull then?

**Comment by goldbattle** [comment]
* Change the `mod.json` to what I posted there
* If the textures added to magical crops work with the beta keep them
* If not, then remove them

**Comment by goldbattle** [comment]
Thanks again!
Everything looks good.

**Pull request merged**
